#coding:utf-8
a=range(6)
b=set({0,1,2,3,4,5})
c=set(a)
d=set([2,5,9,11])
e=set((13,24,35))
print(c==b)
c.update({6,7,8,9})
print(c)
print(b.issubset(c))
print(c.issuperset(a))
print(d.isdisjoint(a))
print(d.isdisjoint(b))
print(b.isdisjoint(c))
print(e.isdisjoint(b))
print('==================交集==============================')
print(e.intersection(b))
print(d & b)
print('==================并集==============================')
print(e.union(b))
print(e | b)
print('==================差集==============================')
print(e.difference(b))
print(e-b)
print(b.difference(e))
print('==================对称差集==============================')
print(d.symmetric_difference(b))
print(d^ b)
print(e^ b)
x=d.symmetric_difference(b)
y=d.difference(b)
z=b.difference(d)
yz=y.union(z)
print(x==yz)
print(x!=yz)
print('==================集合生成==============================')
lst=[i*i for i in range(10)]
print(type(lst))
sbset={i*i for i in range(10)}
print(type(sbset))