#coding:utf-8
lst=['AA','BB','CC','DD','EE','FF','GG','python']
lst.append('hello')
print(lst)
lst1=['Java','C++']
lst.insert(1,lst1)
print(lst)
lst.pop(1)
print(lst)
n_lst=lst[7:9]
lst[7:9]=[]
print(n_lst)
print(lst)
#lst.clear()
#print(lst)
#del lst
lst[1:3]=['CC','BB']
print(lst)
lst2=[11,22,33,44,55,66,77,88,99,00]
print(lst2)
print(id(lst2))
lst2.sort()
print(id(lst2))
print(lst2)
lst2.sort(reverse=True)
print(id(lst2))
print(lst2)
n_lst2=sorted(lst2)
print(id(n_lst2))
print(n_lst2)
n_lst2=sorted(lst2,reverse=True)
print(id(n_lst2))
print(n_lst2)